stages:
  load_data: 
    cmd: python src/stage_01_load_and_save.py --config=params.yaml

    deps:
      - src/stage_01_load_and_save.py
    params: 
      - data_source.s3_source
      - artifacts.raw_local_data
    outs:
      - artifacts/raw_local_data_dir/data.csv